### ISSUE TITLE
readme args order is wrong

### ISSUE THREAD

**Issue by zendesk-yoshi-sono** [heap/heap-ruby#10]
I believe

> heap_client.track 'user-identity', 'event-name', property: 'value'

should be `heap_client.track 'event-name', 'user-identity', property: 'value'` ?

**Comment by pwnall** [comment]
@zendesk-yoshi-sono Thank you very much for catching that! I fixed the README in 0f0a35389eb824e29c1ee099661eb3823653be42.

Please let me know if you run into any other issues using the gem.
