### ISSUE TITLE
How to indentify new user

### ISSUE THREAD

**Issue by dixpac** [heap/heap-ruby#11]
Help me out here how to identify new user! 
I'cant find `Heap#identify` method ?

**Comment by jeffling** [comment]
With the server-side API, you don't need to call `identify`. You specify which user is sending the event on each `track` call. 

In your backend, when registering a new user, you can use the `addUserProperties` method, a new user should automatically be created in heap. 

https://heapanalytics.com/docs/server-side

**Comment by dixpac** [comment]
@jeffling  this doesnt seem to work! When my user logs in I added this line in my rails app
`Heap.add_user_properties current_user.email, name: current_user.name`
But it is not identifying user

**Comment by dixpac** [comment]
I got it to work. by borrowing principle done here
https://github.com/HectorMalot/heap

**Comment by jfyzhao** [comment]
@dixpac How did you end up doing this? Having similar issues - with the syntax in this README it seems to build the request but not actually make the POST to Heap's API

**Comment by dixpac** [comment]
hey @jfyzhao 

I created rails helper like this (sorry for the messed up indentation)
```ruby
module HeapHelper
	def heap_analytics(properties = {})
		config = properties.map {|k,v| "#{k}: #{v}"}.join(", ") if properties.is_a? Hash
		heap_js_block %Q{
			window.heap=window.heap||[],heap.load=function(e,t){window.heap.appid=e,window.heap.config=t=t||{};var n=t.forceSSL||"https:"===document.location.protocol,a=document.createElement("script");a.type="text/javascript",a.async=!0,a.src=(n?"https:":"http:")+"//cdn.heapanalytics.com/js/heap-"+e+".js";var o=document.getElementsByTagName("script")[0];o.parentNode.insertBefore(a,o);for(var r=function(e){return function(){heap.push([e].concat(Array.prototype.slice.call(arguments,0)))}},p=["clearEventProperties","identify","setEventProperties","track","unsetEventProperty"],c=0;c<p.length;c++)heap[p[c]]=r(p[c])};
			heap.load("#{Heap.app_id}", {#{config}});
		}
	end

	def heap_identify(handle, properties = nil)
		body = properties.map {|k,v| ", #{k}: \"#{v}\""}.join if properties.is_a? Hash
		heap_js_block %Q{heap.identify({"email": "#{handle}" #{body}});}
	end

	def heap_set_event_properties(properties = {})
		heap_js_block %Q{heap.setEventProperties(#{properties.to_json});}
	end

	def heap_js_block(content)
		javascript_tag :type => "text/javascript" do
			raw content.html_safe
		end
	end
end
```

in my `application.html.erb` I added heap script and identify user like this:

Add this to the header:
`<%= heap_analytics %>`

Ad this to body:
 `<%= heap_identify(current_user.email, name: current_user.name) if signed_in? %>`


Not the greatest way but it works, been using this in production with no problems :)
