### ISSUE TITLE
Add JRuby to travis-ci

### ISSUE THREAD

**Issue by nadavshatz** [heap/heap-ruby#6]
Hi, We're using Heap for a while now but our stack uses JRuby.
I think it'll be beneficial to add JRuby to the Travis CI tests.

Let me know if you need it and I can try and get a PR for it as well.

**Comment by pwnall** [comment]
@nadavshatz Do you happen to use Travis for your own projects as well? If so, can you please tell me what `rvm` values you use?

I created PR #8 that adds `jruby-18mode` and `jruby-19mode` to the test matrix, but that only seems to cover JRuby 1.7. These tags seem very under-specified, compared to the ones related to MRI.

Thanks!

**Comment by nadavshatz** [comment]
I've actually added some of this on another repo that can give you some more reference.
Here's the PR: https://github.com/rails-api/active_model_serializers/pull/1496

Beyond that, I would highly recommend adding the newer Jruby's that are ruby 2+ compatible.

Another thing you can do which will make it easier for you guys is to not support the same ruby versions on jruby and mri and say so in the Readme - basically support jruby 9+/1.7+ only.

Let me know if I can assist in any other way and cheers for the new gem!
